version: '3'

services:
  backend:
    environment:
      - MYSQL_DATABASE=example-db
      - MYSQL_USER=example-user
      - MYSQL_PASSWORD=password
    build:
      context: src/backend/
    ports:
      - 4000:4000
    depends_on:
      - "db"
  client:
    restart: always
    build:
      context: src/client/
    volumes:
      - ./src/client/src:/var/app/src
    ports:
      - 3000:3000
    depends_on:
      - "backend"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
